### PR TITLE
Docker usage

### PR DESCRIPTION
**Pull request by aminvakil**
I've used it and decided to deploy it on docker, because in many servers I don't have pip installed and don't want to mess with my system-wide packages as I don't know python.

Therefore created this docker image and in case you find it suitable, you can put it here for others to use too.

### CODE REVIEW

**Comment by gkbrk** [comment]
> docker run --rm aminvakil/slowloris example.com

I can't really recommend people to execute code from arbitrary sources, as I control neither dockerhub nor the `aminvakil/slowloris` Dockerfile.

More importantly, I feel that recommending people to have Docker, a whole Linux distribution, and a separate Python installation in order to run a self-contained single-file Python script is completely overkill.

If anyone wants to run a vulnerability testing tool, and wants to do it inside a Linux container, I'm sure they will know how to do that themselves.

**Comment by aminvakil** [comment]
> I can't really recommend people to execute code from arbitrary sources, as I control neither dockerhub nor the `aminvakil/slowloris` Dockerfile.

`aminvakil/slowloris` Dockerfile has been pushed to your repository as well and it can be checked from https://hub.docker.com/r/aminvakil/slowloris/dockerfile. 

> More importantly, I feel that recommending people to have Docker, a whole Linux distribution, and a separate Python installation in order to run a self-contained single-file Python script is completely overkill.

You and I are not recommending people to choose this way, it's an easy way (for many people like me) to test the code without going through installing python and pip system-wide which varies in any linux distribution. This is one of the main reasons docker is so popular, you don't need to install anything and you can be sure that your results are exactly the same as developer. 

For some people installing python and pip are overkill, they can choose whether they want to go through pip process or docker process.

> If anyone wants to run a vulnerability testing tool, and wants to do it inside a Linux container, I'm sure they will know how to do that themselves.

Absolutely. That's why Dockerfile has been added to this pull request as well, so they can build for themselves if they want or change it the way they want.

**Comment by gkbrk** [comment]
> Dockerfile has been pushed to your repository as well

As far as I can tell, that command accesses external resources, not the Dockerfile inside the repo. Since I have never used dockerhub, I am not comfortable endorsing them as a trusted source to execute code from.

> it can be checked from https://hub.docker.com/r/aminvakil/slowloris/dockerfile.

Even if I trusted them, I don't control that dockerhub page, and it even points to a fork of this GitHub repo. It doesn't belong to any of the repo maintainers either. Since I'm not going to check that page every day to see if it points to malicious code, and I can't imagine the other maintainer willing to do this, that Docker command simply can't be on the readme.

> test the code without going through installing python and pip system-wide which varies in any linux distribution

Realistically, how many people fit all of the criteria below?

1. Security researcher or programmer interested in server vulnerabilities
2. Runs a Linux distro
3. That Linux distro does not have Python installed
4. That Linux user interested in security is only coming across Python with the help of this tool
5. They are unable or not willing to install Python through their package manager
6. But they are willing to install Docker, an Alpine Linux container, and Python in the container

I can't imagine it's too many people. But on the off chance one of them is here, they can probably write one command in a temporary Alpine container without needing to fetch a Docker file from the internet.

I'll revisit the issue once this project has multiple dependencies in different programming languages, and various background services that need to communicate. I believe if that happens, we can consider some containerization technologies.

**Comment by aminvakil** [comment]
For future readers I'll maintain the docker image for myself and keep it updated in case main repo has been updated.

Thanks! @gkbrk

**Pull request closed without merging**
