### PR TITLE
add new feature which is config socket_counts

### PR DESCRIPTION
**Pull request by pacozaa**
I add a new feature to let slowloris can be config the socket_counts.

### CODE REVIEW

**Comment by GlumiChan** [comment]
Computerphile? :D

**Comment by pacozaa** [comment]
Busted 😂

**Comment by gkbrk** [comment]
At this point I'm thinking if it would be better to do actual command-line argument parsing, for example `./slowloris.py --count 200 example.com`. Could there be more configuration options?

**Comment by GettingGodlyInThisGame** [comment]
I was planning on doing that

**Comment by GettingGodlyInThisGame** [comment]
It might just be worth doing a rewrite on the code

**Comment by pacozaa** [comment]
I m coding it using [argparse](https://docs.python.org/3.3/library/argparse.html#nargs). What do you guys think?

**Comment by GettingGodlyInThisGame** [comment]
I agree with argparse but I already have most of the code done as for the options, optimizing it shouldn't be that hard.

**Comment by pacozaa** [comment]
See #4

**Pull request closed without merging**
