### PR TITLE
Add MANIFEST.in file

### PR DESCRIPTION
**Pull request by fabaff**
Add documentation files to release.

### CODE REVIEW

**Comment by gkbrk** [comment]
Hey @fabaff.

I'm not familiar with this file, can you tell me what it's used for?

**Comment by fabaff** [comment]
This will make sure that the files are included in the source tarball. The [Fedora package](https://src.fedoraproject.org/rpms/slowloris) should ship at least the license thus that PR.

Further details: https://packaging.python.org/guides/using-manifest-in/

P.S.: Could you please make a new release after merging? Thank you.

**Comment by gkbrk** [comment]
@fabaff Made a new release on PyPI, v0.2.1.

Please let me know if there are any other issues.

**Comment by fabaff** [comment]
Thanks for your support to get this sorted out. Stay safe and healthy.

**Pull request merged**
